name: Build Test

on:
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  VITE_PUBLIC_BASE_URL: https://thenextlvl.net
  VITE_FASTSTATS_SCRIPT_URL: https://faststats.dev/script.js
  VITE_FASTSTATS_SITEKEY: afe13ffcfce9ea60d8fc944b903cd605

jobs:
  build-and-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/cache@v5
        with:
          path: ~/.bun/install/cache
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: bun-${{ runner.os }}-
      - run: bun install
      - run: bun run build
